# Generated by Django 5.2.3 on 2025-06-26 03:00

import apps.pacientes.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=20, unique=True, verbose_name='Cédula de Identidad')),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=apps.pacientes.models.patient_photo_path)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('pais', models.CharField(default='Bolivia', max_length=100)),
                ('emergencia_nombre', models.CharField(max_length=200)),
                ('emergencia_telefono', models.CharField(max_length=20)),
                ('emergencia_parentesco', models.CharField(choices=[('padre', 'Padre'), ('madre', 'Madre'), ('hermano', 'Hermano/a'), ('hijo', 'Hijo/a'), ('pareja', 'Cónyuge/Pareja'), ('amigo', 'Amigo/a'), ('otro', 'Otro')], max_length=20)),
                ('grupo_sanguineo', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('desconocido', 'Desconocido')], max_length=20, null=True)),
                ('medicamentos', models.TextField(blank=True, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('enfermedades_cronicas', models.TextField(blank=True, null=True)),
                ('tiene_seguro', models.BooleanField(default=False)),
                ('seguro_compania', models.CharField(blank=True, max_length=100, null=True)),
                ('seguro_poliza', models.CharField(blank=True, max_length=100, null=True)),
                ('seguro_cobertura', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('tratamiento', 'En Tratamiento'), ('moroso', 'Moroso')], default='activo', max_length=20)),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('ultima_visita', models.DateField(blank=True, null=True)),
                ('consentimiento_datos', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
