# Generated by Django 5.2.3 on 2025-06-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='como_localizo',
            field=models.CharField(blank=True, choices=[('referencia', 'Me envió alguien'), ('redes_sociales', 'Redes Sociales'), ('publicidad', 'Publicidad/Anuncios'), ('internet', 'Búsqueda en Internet'), ('pasaba_por_aqui', 'Pasaba por aquí'), ('recomendacion', 'Recomendación profesional'), ('otro', 'Otro')], max_length=50, null=True, verbose_name='¿Cómo nos localizó?'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='como_localizo_detalle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Detalles adicionales'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupación'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='vacuna_covid',
            field=models.BooleanField(default=False, verbose_name='Vacuna contra COVID-19'),
        ),
    ]
