# Generated by Django 5.2.3 on 2025-06-26 18:04

import apps.historias_clinicas.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias_clinicas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=apps.historias_clinicas.models.foto_clinica_path)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='historias_clinicas.examenclinico')),
            ],
            options={
                'verbose_name': 'Foto Clínica',
                'verbose_name_plural': 'Fotos Clínicas',
            },
        ),
    ]
